default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: taitasu2

development:
  <<: *default
  database: kuchikomi_elevator_development

test:
  <<: *default
  database: kuchikomi_elevator_test

production:
  <<: *default
  database: kuchikomi_elevator_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock